[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.i686-unknown-linux-musl]
linker = "rust-lld"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"

[env]
CC_i686_unknown_linux_musl = "i686-linux-gnu-gcc"
CC_x86_64_unknown_linux_musl = "x86_64-linux-gnu-gcc"
CC_aarch64_unknown_linux_musl = "aarch64-linux-gnu-gcc"
